name: Pipeline docker image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Test app
      run: mvn test

    - name: Build jar artifact
      run: mvn -B package --file pom.xml

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u alefh --password-stdin

    - name: Build the version of app
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:5})

    - name: Build the tagged Docker image
      run: docker build -t alefh/ci-docker-image:${{steps.vars.outputs.tag}} .

    - name: Push the tagged Docker image
      run: docker push alefh/ci-docker-image:${{steps.vars.outputs.tag}}

    - name: Build the latest Docker image
      run: docker build -t alefh/ci-docker-image:latest .

    - name: Push the latest Docker image
      run: docker push alefh/ci-docker-image:latest

  push_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Test app
      run: mvn test

    - name: Build jar artifact
      run: mvn -B package --file pom.xml

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: alefh/ci-docker-image-action
        tag_with_ref: true